[package]
name = "dfloat-rops"
version = "0.0.3"
authors = ["GNQG <my.t.gnq@gmail.com>"]

[dependencies]
float-traits = "^0.0.3"
safeeft = "^0.0.5"
roundops = {path = "../roundops"}
dfloat = {path = "../dfloat"}
fma = {version = "^0.1.0", optional = true}

[dev-dependencies]
rand = "*"

[features]
use-fma = ["fma", "safeeft/use-fma", "roundops/use-fma"]
